#!/usr/bin/env bun
/**
 * Generate Item ID Mapping
 *
 * Reads all item manifests and generates a deterministic bidirectional
 * mapping between string IDs and numeric IDs. Outputs:
 * 1. A TypeScript file with the mapping as a constant record
 * 2. Console summary of all items
 *
 * Run: bun packages/web3/src/mapping/generate-item-ids.ts
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { buildItemIdMap, getManifestsDir } from "./ItemIdMapping.js";

async function main() {
  const manifestsDir = getManifestsDir();
  console.log(`[generate-item-ids] Reading manifests from: ${manifestsDir}`);

  const mapping = await buildItemIdMap(manifestsDir);

  console.log(`[generate-item-ids] Base items: ${mapping.baseItemCount}`);
  console.log(
    `[generate-item-ids] Total items (with noted): ${mapping.totalItemCount}`,
  );

  // Generate TypeScript output
  const stringToNumericEntries: string[] = [];
  const numericToStringEntries: string[] = [];

  // Sort by numeric ID for consistent output
  const sortedByNumeric = [...mapping.numericToString.entries()].sort(
    (a, b) => a[0] - b[0],
  );

  for (const [numericId, stringId] of sortedByNumeric) {
    stringToNumericEntries.push(`  "${stringId}": ${numericId}`);
    numericToStringEntries.push(`  ${numericId}: "${stringId}"`);
  }

  const output = `// AUTO-GENERATED by generate-item-ids.ts -- DO NOT EDIT MANUALLY
// Generated from ${mapping.baseItemCount} base items + noted variants = ${mapping.totalItemCount} total

/**
 * Maps string item IDs to numeric IDs for on-chain use.
 * Noted items have numericId = baseId + 10000.
 */
export const STRING_TO_NUMERIC: Record<string, number> = {
${stringToNumericEntries.join(",\n")},
};

/**
 * Maps numeric item IDs back to string IDs.
 */
export const NUMERIC_TO_STRING: Record<number, string> = {
${numericToStringEntries.join(",\n")},
};

/** Total number of base items (excluding noted variants) */
export const BASE_ITEM_COUNT = ${mapping.baseItemCount};

/** Total number of items including noted variants */
export const TOTAL_ITEM_COUNT = ${mapping.totalItemCount};

/** Offset for noted item IDs: notedId = baseId + NOTED_ITEM_OFFSET */
export const NOTED_ITEM_OFFSET = 10000;

/**
 * Get the numeric ID for a string item ID.
 * Returns 0 if the item is not found.
 */
export function getNumericId(stringId: string): number {
  return STRING_TO_NUMERIC[stringId] ?? 0;
}

/**
 * Get the string ID for a numeric item ID.
 * Returns empty string if the item is not found.
 */
export function getStringId(numericId: number): string {
  return NUMERIC_TO_STRING[numericId] ?? "";
}
`;

  const outputPath = join(import.meta.dirname, "item-id-map.generated.ts");
  await writeFile(outputPath, output, "utf-8");

  console.log(`[generate-item-ids] Written to: ${outputPath}`);

  // Print first 10 items as preview
  console.log("\n[generate-item-ids] Preview (first 10):");
  let count = 0;
  for (const [numericId, stringId] of sortedByNumeric) {
    if (count >= 10) break;
    console.log(`  ${numericId} → ${stringId}`);
    count++;
  }
  if (mapping.totalItemCount > 10) {
    console.log(`  ... and ${mapping.totalItemCount - 10} more`);
  }
}

main().catch((err) => {
  console.error("[generate-item-ids] Failed:", err);
  process.exit(1);
});
