// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

import { System } from "@latticexyz/world/src/System.sol";
import { TradeSession, TradeOffer, TradeLog, InventorySlot, GoldBalance, ItemBalance, CharacterOwner, PlayerRegistry } from "../codegen/index.sol";
import { TradeStatus } from "../codegen/common.sol";
import { Constants } from "../libraries/Constants.sol";
import { Errors } from "../libraries/Errors.sol";

/**
 * @title TradeSystem
 * @notice On-chain escrow for player-to-player trading. PUBLIC access.
 * Flow: createTrade → offerItem/offerGold → acceptTrade (both) → atomic swap.
 * Cancel returns all escrowed assets. Players pay gas for trades.
 */
contract TradeSystem is System {
    /**
     * @notice Create a new trade session between two players.
     * Called by the server operator after both players agree to trade.
     *
     * @param tradeId Unique trade ID (generated by server)
     * @param initiatorAddress Initiator's wallet address
     * @param recipientAddress Recipient's wallet address
     */
    function createTrade(
        bytes32 tradeId,
        address initiatorAddress,
        address recipientAddress
    ) public {
        address caller = _msgSender();
        if (caller != initiatorAddress && caller != recipientAddress) {
            revert Errors.NotTradeParticipant(tradeId, caller);
        }
        if (initiatorAddress == recipientAddress) revert Errors.SelfTrade();
        if (initiatorAddress == address(0) || recipientAddress == address(0)) revert Errors.InvalidAddress();

        // Verify both players are registered
        bytes32 initiatorCharId = PlayerRegistry.getCharacterId(initiatorAddress);
        bytes32 recipientCharId = PlayerRegistry.getCharacterId(recipientAddress);
        if (initiatorCharId == bytes32(0)) revert Errors.PlayerNotRegistered(initiatorAddress);
        if (recipientCharId == bytes32(0)) revert Errors.PlayerNotRegistered(recipientAddress);

        // Check trade doesn't already exist
        address existingInitiator = TradeSession.getInitiator(tradeId);
        if (existingInitiator != address(0)) revert Errors.TradeAlreadyCompleted(tradeId);

        TradeSession.set(
            tradeId,
            initiatorAddress,
            recipientAddress,
            initiatorCharId,
            recipientCharId,
            TradeStatus.Active,
            false, // initiatorAccepted
            false, // recipientAccepted
            0,     // initiatorGold
            0,     // recipientGold
            uint64(block.timestamp)
        );
    }

    /**
     * @notice Offer an item from inventory into trade escrow.
     * The item is moved from InventorySlot to TradeOffer and ERC-1155 balance
     * is transferred from player to the World contract (escrow).
     *
     * @param tradeId The trade session ID
     * @param inventorySlot The inventory slot to offer from
     * @param quantity Amount to offer (for stackable items)
     */
    function offerItem(
        bytes32 tradeId,
        uint8 inventorySlot,
        uint32 quantity
    ) public {
        address caller = _msgSender();
        _requireActiveTradeParticipant(tradeId, caller);

        if (quantity == 0) revert Errors.ZeroAmount();
        if (inventorySlot >= Constants.MAX_INVENTORY_SLOTS) revert Errors.InvalidSlotIndex(inventorySlot);

        // Determine which side the caller is on
        address initiator = TradeSession.getInitiator(tradeId);
        uint8 side = (caller == initiator) ? 0 : 1;
        bytes32 characterId = (side == 0)
            ? TradeSession.getInitiatorCharId(tradeId)
            : TradeSession.getRecipientCharId(tradeId);

        // Read item from inventory
        uint32 itemId = InventorySlot.getItemId(characterId, inventorySlot);
        uint32 available = InventorySlot.getQuantity(characterId, inventorySlot);
        if (itemId == Constants.EMPTY_ITEM_ID || available == 0) {
            revert Errors.InventorySlotEmpty(characterId, inventorySlot);
        }
        if (available < quantity) {
            revert Errors.InsufficientQuantity(characterId, inventorySlot, quantity, available);
        }

        // Find next available offer index for this side
        uint8 offerIndex = _findNextOfferIndex(tradeId, side);
        if (offerIndex >= Constants.MAX_TRADE_OFFERS) revert Errors.TradeOffersFull(tradeId, side);

        // Move item from inventory to escrow
        uint32 remaining = available - quantity;
        if (remaining == 0) {
            InventorySlot.deleteRecord(characterId, inventorySlot);
        } else {
            InventorySlot.setQuantity(characterId, inventorySlot, remaining);
        }

        // Record the offer
        TradeOffer.set(tradeId, side, offerIndex, itemId, quantity, inventorySlot);

        // Transfer ERC-1155 balance from player to World (escrow)
        uint256 currentBalance = ItemBalance.getBalance(caller, uint256(itemId));
        if (currentBalance >= quantity) {
            ItemBalance.set(caller, uint256(itemId), currentBalance - quantity);
        }
        // Escrow balance tracked implicitly via TradeOffer records

        // Reset acceptance flags (any change invalidates previous acceptance)
        TradeSession.setInitiatorAccepted(tradeId, false);
        TradeSession.setRecipientAccepted(tradeId, false);
    }

    /**
     * @notice Offer gold in the trade.
     * @param tradeId The trade session ID
     * @param amount Gold amount to offer
     */
    function offerGold(bytes32 tradeId, uint64 amount) public {
        address caller = _msgSender();
        _requireActiveTradeParticipant(tradeId, caller);

        if (amount == 0) revert Errors.ZeroAmount();

        address initiator = TradeSession.getInitiator(tradeId);
        uint8 side = (caller == initiator) ? 0 : 1;
        bytes32 characterId = (side == 0)
            ? TradeSession.getInitiatorCharId(tradeId)
            : TradeSession.getRecipientCharId(tradeId);

        // Verify player has enough gold
        uint64 currentGold = GoldBalance.getAmount(characterId);
        if (currentGold < amount) revert Errors.InsufficientGold(characterId, amount, currentGold);

        // Move gold to escrow
        GoldBalance.set(characterId, currentGold - amount);

        // Record gold offer (add to existing offer if any)
        if (side == 0) {
            uint64 existing = TradeSession.getInitiatorGold(tradeId);
            TradeSession.setInitiatorGold(tradeId, existing + amount);
        } else {
            uint64 existing = TradeSession.getRecipientGold(tradeId);
            TradeSession.setRecipientGold(tradeId, existing + amount);
        }

        // Reset acceptance flags
        TradeSession.setInitiatorAccepted(tradeId, false);
        TradeSession.setRecipientAccepted(tradeId, false);
    }

    /**
     * @notice Accept the current trade offers.
     * When both sides accept, the trade completes automatically.
     * @param tradeId The trade session ID
     */
    function acceptTrade(bytes32 tradeId) public {
        address caller = _msgSender();
        _requireActiveTradeParticipant(tradeId, caller);

        address initiator = TradeSession.getInitiator(tradeId);
        bool isInitiator = (caller == initiator);

        // Set acceptance flag
        if (isInitiator) {
            TradeSession.setInitiatorAccepted(tradeId, true);
        } else {
            TradeSession.setRecipientAccepted(tradeId, true);
        }

        // Check if both accepted
        bool bothAccepted = TradeSession.getInitiatorAccepted(tradeId)
            && TradeSession.getRecipientAccepted(tradeId);

        if (bothAccepted) {
            _completeTrade(tradeId);
        }
    }

    /**
     * @notice Cancel the trade. All escrowed items/gold return to original owners.
     * @param tradeId The trade session ID
     */
    function cancelTrade(bytes32 tradeId) public {
        TradeStatus status = TradeSession.getStatus(tradeId);
        if (status != TradeStatus.Active && status != TradeStatus.Confirming) {
            revert Errors.TradeNotActive(tradeId);
        }

        address caller = _msgSender();
        address initiator = TradeSession.getInitiator(tradeId);
        address recipient = TradeSession.getRecipient(tradeId);
        if (caller != initiator && caller != recipient) {
            revert Errors.NotTradeParticipant(tradeId, caller);
        }

        // Return all escrowed items to original owners
        _returnEscrowedItems(tradeId, 0); // Return initiator's items
        _returnEscrowedItems(tradeId, 1); // Return recipient's items

        // Return escrowed gold
        bytes32 initiatorCharId = TradeSession.getInitiatorCharId(tradeId);
        bytes32 recipientCharId = TradeSession.getRecipientCharId(tradeId);

        uint64 initiatorGold = TradeSession.getInitiatorGold(tradeId);
        uint64 recipientGold = TradeSession.getRecipientGold(tradeId);

        if (initiatorGold > 0) {
            uint64 currentGold = GoldBalance.getAmount(initiatorCharId);
            GoldBalance.set(initiatorCharId, currentGold + initiatorGold);
        }
        if (recipientGold > 0) {
            uint64 currentGold = GoldBalance.getAmount(recipientCharId);
            GoldBalance.set(recipientCharId, currentGold + recipientGold);
        }

        TradeSession.setStatus(tradeId, TradeStatus.Cancelled);
    }

    // =========================================================================
    // Internal: Trade Completion
    // =========================================================================

    /**
     * @dev Complete the trade: swap items and gold between players.
     */
    function _completeTrade(bytes32 tradeId) internal {
        address initiator = TradeSession.getInitiator(tradeId);
        address recipient = TradeSession.getRecipient(tradeId);
        bytes32 initiatorCharId = TradeSession.getInitiatorCharId(tradeId);
        bytes32 recipientCharId = TradeSession.getRecipientCharId(tradeId);

        // Transfer initiator's offered items → recipient's inventory
        _transferOfferedItems(tradeId, 0, recipientCharId, recipient);

        // Transfer recipient's offered items → initiator's inventory
        _transferOfferedItems(tradeId, 1, initiatorCharId, initiator);

        // Transfer gold
        uint64 initiatorGold = TradeSession.getInitiatorGold(tradeId);
        uint64 recipientGold = TradeSession.getRecipientGold(tradeId);

        if (initiatorGold > 0) {
            uint64 currentGold = GoldBalance.getAmount(recipientCharId);
            GoldBalance.set(recipientCharId, currentGold + initiatorGold);
        }
        if (recipientGold > 0) {
            uint64 currentGold = GoldBalance.getAmount(initiatorCharId);
            GoldBalance.set(initiatorCharId, currentGold + recipientGold);
        }

        // Mark trade as completed
        TradeSession.setStatus(tradeId, TradeStatus.Completed);

        // Write offchain trade log
        TradeLog.set(
            tradeId,
            initiator,
            recipient,
            initiatorGold,
            recipientGold,
            uint64(block.timestamp)
        );
    }

    /**
     * @dev Transfer offered items from escrow to receiving player's inventory.
     */
    function _transferOfferedItems(
        bytes32 tradeId,
        uint8 side,
        bytes32 receiverCharId,
        address receiverAddress
    ) internal {
        for (uint8 i = 0; i < Constants.MAX_TRADE_OFFERS; i++) {
            uint32 itemId = TradeOffer.getItemId(tradeId, side, i);
            if (itemId == Constants.EMPTY_ITEM_ID) continue;

            uint32 quantity = TradeOffer.getQuantity(tradeId, side, i);
            if (quantity == 0) continue;

            // Find first empty inventory slot for receiver
            uint8 targetSlot = _findEmptyInventorySlot(receiverCharId);
            if (targetSlot < Constants.MAX_INVENTORY_SLOTS) {
                // Place in inventory
                InventorySlot.set(receiverCharId, targetSlot, itemId, quantity);
                // Update ERC-1155 balance
                uint256 currentBalance = ItemBalance.getBalance(receiverAddress, uint256(itemId));
                ItemBalance.set(receiverAddress, uint256(itemId), currentBalance + quantity);
            }
            // If inventory is full, items are lost (server should pre-validate)
            // In practice the server checks inventory space before accepting

            // Clean up offer record
            TradeOffer.deleteRecord(tradeId, side, i);
        }
    }

    /**
     * @dev Return escrowed items back to the original owner's inventory.
     */
    function _returnEscrowedItems(bytes32 tradeId, uint8 side) internal {
        bytes32 characterId = (side == 0)
            ? TradeSession.getInitiatorCharId(tradeId)
            : TradeSession.getRecipientCharId(tradeId);
        address playerAddress = (side == 0)
            ? TradeSession.getInitiator(tradeId)
            : TradeSession.getRecipient(tradeId);

        for (uint8 i = 0; i < Constants.MAX_TRADE_OFFERS; i++) {
            uint32 itemId = TradeOffer.getItemId(tradeId, side, i);
            if (itemId == Constants.EMPTY_ITEM_ID) continue;

            uint32 quantity = TradeOffer.getQuantity(tradeId, side, i);
            if (quantity == 0) continue;

            uint8 sourceSlot = TradeOffer.getSourceSlot(tradeId, side, i);

            // Try to return to original slot first
            uint32 existingItem = InventorySlot.getItemId(characterId, sourceSlot);
            if (existingItem == Constants.EMPTY_ITEM_ID) {
                InventorySlot.set(characterId, sourceSlot, itemId, quantity);
            } else {
                // Original slot is occupied, find any empty slot
                uint8 emptySlot = _findEmptyInventorySlot(characterId);
                if (emptySlot < Constants.MAX_INVENTORY_SLOTS) {
                    InventorySlot.set(characterId, emptySlot, itemId, quantity);
                }
                // If inventory is completely full, item goes to bank (TODO: bank overflow)
            }

            // Restore ERC-1155 balance
            uint256 currentBalance = ItemBalance.getBalance(playerAddress, uint256(itemId));
            ItemBalance.set(playerAddress, uint256(itemId), currentBalance + quantity);

            // Clean up offer record
            TradeOffer.deleteRecord(tradeId, side, i);
        }
    }

    // =========================================================================
    // Internal: Helpers
    // =========================================================================

    function _requireActiveTradeParticipant(bytes32 tradeId, address caller) internal view {
        TradeStatus status = TradeSession.getStatus(tradeId);
        if (status != TradeStatus.Active) revert Errors.TradeNotActive(tradeId);

        address initiator = TradeSession.getInitiator(tradeId);
        address recipient = TradeSession.getRecipient(tradeId);
        if (caller != initiator && caller != recipient) {
            revert Errors.NotTradeParticipant(tradeId, caller);
        }
    }

    function _findNextOfferIndex(bytes32 tradeId, uint8 side) internal view returns (uint8) {
        for (uint8 i = 0; i < Constants.MAX_TRADE_OFFERS; i++) {
            uint32 itemId = TradeOffer.getItemId(tradeId, side, i);
            if (itemId == Constants.EMPTY_ITEM_ID) return i;
        }
        return Constants.MAX_TRADE_OFFERS; // All slots full
    }

    function _findEmptyInventorySlot(bytes32 characterId) internal view returns (uint8) {
        for (uint8 i = 0; i < Constants.MAX_INVENTORY_SLOTS; i++) {
            uint32 itemId = InventorySlot.getItemId(characterId, i);
            if (itemId == Constants.EMPTY_ITEM_ID) return i;
        }
        return Constants.MAX_INVENTORY_SLOTS; // No empty slot
    }
}
